stages:
  - build

build-linux-job:
  image: enderthecoder/oatpp-dev:1.0
  stage: build
  script:
    - echo "Running build"
    - mkdir server/build-linux && cd server/build-linux
    - cmake -G "Ninja Multi-Config"  ..
    - cmake --build . -j --config Release
  artifacts:
    expire_in: 1 week
    name: linux-gcc-x64-standalone-server-${CI_PIPELINE_ID}
    paths:
      - server/build-linux/Release/ender_label-exe
  tags:
    - docker