stages:
  - build

build-linux-job:
  image: enderthecoder/oatpp-dev:latest
  stage: build
  script:
    - echo "Running build"
    - mkdir build-linux && cd build-linux
    - cmake -G "Ninja Multi-Config"  -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -DCMAKE_C_COMPILER=/usr/bin/gcc-14 -DCMAKE_CXX_COMPILER=/usr/bin/g++-14 ..
    - cmake --build . -j --config Release
  artifacts:
    expire_in: 1 week
    name: linux-gcc-x64-standalone-server-${CI_PIPELINE_ID}
    paths:
      - build-linux/Release/ender-label-exe
  tags:
    - docker
build-docker-job:
  stage: build
  script:
    - docker build --pull -t enderthecoder/ender-label-backend .
    - docker push enderthecoder/ender-label-backend
  tags:
    - linux